extends: stylelint-config-recommended-scss
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  at-rule-empty-line-before:
    - always
    -
      except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
  at-rule-name-space-after: always
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-before: always
  color-named: never
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always
  declaration-empty-line-before:
    - always
    -
      except:
        - after-declaration
        - first-nested
      ignore:
        - after-comment
  declaration-no-important: true
  function-comma-space-after: always
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-name-case: lower
  indentation: 4
  length-zero-no-unit: true
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  number-leading-zero: never
  number-no-trailing-zeros: true
  property-no-vendor-prefix: true
  rule-empty-line-before:
    - always
    -
      except:
        - first-nested
      ignore:
        - after-comment
  selector-class-pattern: ^[a-z]+(-[a-z]+)*$
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-max-id: 0
  selector-pseudo-element-colon-notation: double
  shorthand-property-no-redundant-values: true
  string-quotes: double
  unit-case: lower
  value-keyword-case: lower
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
  max-empty-lines: 1
  scss/double-slash-comment-empty-line-before: always
  scss/double-slash-comment-whitespace-inside: always
  order/order:
    - dollar-variables
    -
      type: at-rule
      name: extend
    - declarations
    - at-rules
    - rules
  order/properties-order:
    -
      # Positioning
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      # Display and box model
      - display
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order
      - box-sizing
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
    - unspecified: bottomAlphabetical
